version: '3.5'
services:
  tinyproxy:
    image: docker.io/kalaksi/tinyproxy
    # You can also use GitLab as an alternative to Docker Hub:
    # image: registry.gitlab.com/kalaksi-containers/tinyproxy
    restart: unless-stopped
    cap_drop:
      - ALL
    ports:
      - 8888:8888
    environment:
      DISABLE_VIA_HEADER: 'yes'
      STAT_HOST: tinyproxy.stats
      MAX_CLIENTS: 100
      ALLOWED_NETWORKS: 10.0.0.0/8
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888"]
      interval: 5m
      timeout: 10s
      retries: 1
